- name: Setup Frontend Component
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Copy ansible configuration file
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Setup NodeJS repo
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

    - name: Install NodejS
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Remove App content folder
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create App content folder
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download frontend content
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/frontend-compiled.zip
        dest: /usr/share/nginx/html
        remote_src: yes

# Since npm build is failing, we moved to download the direct compiled code.
#     - name: Build static code
#       ansible.builtin.shell: npm cache clean --force ; npm install ; npm run build ; rm -rf /usr/share/nginx/html/* ; cp -r out/* /usr/share/nginx/html/
#       args:
#         chdir: /tmp/frontend

    - name: Start Nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: yes


